### ISSUE TITLE
Mbedtls error: The connection indicated an EOF

### ISSUE THREAD

**Issue by copercini** [loboris/ESP32-PPPOS-EXAMPLE#2]
My GPRS connection is not so good, so many times I just got:
`E (336027) [HTTPS]: Last error was: -0x7280 - SSL - The connection indicated an EOF`
during handshake. 

EDIT: That's occur only on weak signal, and mbedtls try handshake before receive all data
![screenshot_1](https://cloud.githubusercontent.com/assets/21266776/26465963/7991bb7e-4163-11e7-8c8c-0b030004caef.png)

There is any way to reduce this problem?

**Comment by loboris** [comment]
This was intended just as the simple example to demonstrate that ESP32 can work with GPRS with no major problems.
I'm working on more complex and complete GSM/pppos **library** and an example with libcurl. I expect to push it on GitHub in a week or two.
Thank you for your comments and suggestions (in pull request).
