### ISSUE TITLE
ESP32-PPPOS-EXAMPLE / "lwip/pppapi.h" include issue

### ISSUE THREAD

**Issue by Halabdelkrim** [loboris/ESP32-PPPOS-EXAMPLE#22]
Hello,

I want to use "ESP32-PPPOS-EXAMPLE" example to create a small project using SIM900 to send and receive SMS.

But when i tried to build the project i faced an error with the "lwip/pppapi.h" library.

`#warning "esp_event_loop.h is deprecated, please include esp_event.h instead"
  ^~~~~~~
../main/pppos_client_main.c:33:10: fatal error: lwip/pppapi.h: No such file or directory
 #include "lwip/pppapi.h"
          ^~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
ninja failed with exit code 1`

Is there any solution to solve this issue ?

Thank you in advance.

**Comment by AliGhorbani3** [comment]
I have the same problem, any solutions?

**Comment by Halabdelkrim** [comment]
Unfortunately no.
