### ISSUE TITLE
Cannot obtain an IP and losing connection

### ISSUE THREAD

**Issue by xvinny-zz** [loboris/ESP32-PPPOS-EXAMPLE#7]
Hi all,

I'm testing some different SIM cards (of different carriers) and there is one that isn't working.
Folow the log:

[0;32mI (346318) [PPPOS CLIENT]: AT COMMAND: [AT..][0m
[0;32mI (346341) [PPPOS CLIENT]: AT RESPONSE: [..OK..][0m
[0;32mI (346441) [PPPOS CLIENT]: AT COMMAND: [ATZ..][0m
[0;32mI (346464) [PPPOS CLIENT]: AT RESPONSE: [..OK..][0m
[0;32mI (346564) [PPPOS CLIENT]: AT COMMAND: [ATE0..][0m
[0;32mI (346587) [PPPOS CLIENT]: AT RESPONSE: [ATE0...OK..][0m
[0;32mI (346687) [PPPOS CLIENT]: AT COMMAND: [AT+CFUN=1..][0m
[0;32mI (346710) [PPPOS CLIENT]: AT RESPONSE: [..OK..][0m
[0;32mI (347810) [PPPOS CLIENT]: AT COMMAND: [AT+CNMI=0,0,0,0,0..][0m
[0;32mI (347834) [PPPOS CLIENT]: AT RESPONSE: [..OK..][0m
[0;32mI (347934) [PPPOS CLIENT]: AT COMMAND: [AT+CPIN?..][0m
[0;32mI (347958) [PPPOS CLIENT]: AT RESPONSE: [..+CPIN: READY....OK..][0m
[0;32mI (348058) [PPPOS CLIENT]: AT COMMAND: [AT+CREG?..][0m
[0;32mI (348082) [PPPOS CLIENT]: AT RESPONSE: [..+CREG: 0,1....OK..][0m
[0;32mI (348182) [PPPOS CLIENT]: AT COMMAND: [AT+CGDCONT=1,"IP","zap.vivo.com.br"..][0m
[0;32mI (348213) [PPPOS CLIENT]: AT RESPONSE: [..OK..][0m
[0;32mI (348313) [PPPOS CLIENT]: AT COMMAND: [AT+CGDATA="PPP",1..][0m
[0;32mI (348338) [PPPOS CLIENT]: AT RESPONSE: [..CONNECT..][0m
[0;32mI (349338) [PPPOS CLIENT]: GSM initialized.[0m
[0;31mE (355535) [PPPOS CLIENT]: status_cb: Connection lost[0m
 [0;31mE (355559) [PPPOS CLIENT]: Disconnected, trying again...[0m
[0;33mW (355559) [PPPOS CLIENT]: status_cb: User interrupt (disconnected)[0m

I thought that the problem could be signal strength, but the signal here is good.
What could be?

Best regards,

Vinicius

**Comment by rtecnica** [comment]
I'm getting a similar problem where I'm able to get an IP at first, but later connections fail to obtain an IP address in the same way you describe.

I can fix it if I turn everything off, wait a bit and try again. 

I'm thinking maybe this is a network issue?

**Comment by HarshilSoni43** [comment]
i'm also getting the same issue.

I have checked the network strength using command AT+CSQ it gives excellent signal strength.

so as per this logs i'm getting same problem of rapid disconnection and IP obtaining delay.

I have used different sim cards but issue is same.

I have tested my ppp connection with Linux system it works properly without rapid disconnection.

and  sometimes ppp connection closed from modem but i'm not getting the disconnect event in call back  in esp side for ppp auto recover mechanism .

please provide solution for above issues if possible.

**Comment by Anderson-R** [comment]
I'm having this same issue. Have any of you found a solution?

**Comment by xvinny-zz** [comment]
The problem was with the carrier signal.. I changed the SIM to other carrier and worked.
Anyways, I discovered later that the most efficient solution is to adopt the ESP32-Arduino and use TinyGSM library. Doing it, you'll be more productive.
